// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeqowVdCNg0GDcGa5JTlmPhunsomKfGLs',
    appId: '1:760353982981:web:9a8b7213cdfaaece74aa6c',
    messagingSenderId: '760353982981',
    projectId: 'oventes-9000d',
    authDomain: 'oventes-9000d.firebaseapp.com',
    storageBucket: 'oventes-9000d.firebasestorage.app',
    measurementId: 'G-V7C7GEGTNZ',
    databaseURL: 'https://oventes-9000d-default-rtdb.asia-southeast1.firebasedatabase.app/'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxN0VeinYBE2Ee4GNNnUu2kOVAqyGIk98',
    appId: '1:760353982981:android:6bde51edfc7fc98174aa6c',
    messagingSenderId: '760353982981',
    projectId: 'oventes-9000d',
    storageBucket: 'oventes-9000d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAanMlrDX5vbUoK8yKGI9DwfLJzalZHjsI',
    appId: '1:760353982981:ios:c791887c27a4b1c374aa6c',
    messagingSenderId: '760353982981',
    projectId: 'oventes-9000d',
    storageBucket: 'oventes-9000d.firebasestorage.app',
    iosBundleId: 'com.example.firstTryMob',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAanMlrDX5vbUoK8yKGI9DwfLJzalZHjsI',
    appId: '1:760353982981:ios:c791887c27a4b1c374aa6c',
    messagingSenderId: '760353982981',
    projectId: 'oventes-9000d',
    storageBucket: 'oventes-9000d.firebasestorage.app',
    iosBundleId: 'com.example.firstTryMob',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeqowVdCNg0GDcGa5JTlmPhunsomKfGLs',
    appId: '1:760353982981:web:5b077122877ed03474aa6c',
    messagingSenderId: '760353982981',
    projectId: 'oventes-9000d',
    authDomain: 'oventes-9000d.firebaseapp.com',
    storageBucket: 'oventes-9000d.firebasestorage.app',
    measurementId: 'G-JML5EJEP8B',
  );
}
